---
# TODO: http://willthames.github.io/2016/09/21/using-command-and-shell-in-ansible.html
# TODO: https://github.com/ansible/ansible-lint/issues/497
- name: '{{ ansible_distribution }} - Telegraf: Add repository InfluxDB for telegraf from influxdata'
  shell: |
    cat <<EOF | sudo tee /etc/apt/sources.list.d/influxdata.list
    deb https://repos.influxdata.com/ubuntu bionic stable
    EOF
    sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
    apt-get update
  become: true
  when: ansible_distribution == 'Ubuntu'
  environment: "{{ http_proxy | default({}) }}"


# TODO: http://willthames.github.io/2016/09/21/using-command-and-shell-in-ansible.html
# TODO: https://github.com/ansible/ansible-lint/issues/497
- name: '{{ ansible_distribution }} - Telegraf: Add repository InfluxDB for telegraf from influxdata'
  shell: |
    sudo apt-get update && sudo apt-get install apt-transport-https
    curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
    echo "deb https://repos.influxdata.com/debian stretch stable" | sudo tee /etc/apt/sources.list.d/influxdb.list
  become: true
  when: ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch'
  environment: "{{ http_proxy | default({}) }}"

- name: "Run the equivalent of 'apt-get update' as a separate step"
  apt:
    update_cache: yes
  become: true
  environment: "{{ http_proxy | default({}) }}"

# Installing telegraf agent
- name: "Telegraf: Install agent {{ base_telegraf_service_name }}"
  apt:
    name: "{{ base_telegraf_service_name }}"
  become: true
  environment: "{{ http_proxy | default({}) }}"


- name: "Python: Installing packages {{ base_telegraf_debian_python_package }}"
  apt:
    name: "{{ base_telegraf_debian_python_package }}"
  become: yes
  environment: "{{ http_proxy | default({}) }}"


- name: "Python: python{{ base_telegraf_debian_python_version }} -m pip install packages"
  shell: "python{{ base_telegraf_python_version }} -m pip install --proxy='{{ http_proxy }}' {{ item }}"
  with_items:
    - "{{ base_telegraf_pip_modules }}"
  become: yes
  environment: "{{ http_proxy | default() }}"
