---
- include: redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: debian.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- include: telegraf.yml
  tags: [deploy_telegraf]
