---

- name: '{{ ansible_distribution }} - Telegraf: Add repository InfluxDB for telegraf from influxdata'
  yum_repository:
    name: "InfluxDB"
    description: "InfluxDB Yum Repository"
    baseurl: 'https://repos.influxdata.com/rhel/$releasever/$basearch/stable'
    enabled: true
    gpgcheck: true
    gpgkey: "https://repos.influxdata.com/influxdb.key"
  become: true


# Installing telegraf agent
- name: "Telegraf: Install agent {{ base_telegraf_service_name }}"
  package:
    name: "{{ base_telegraf_service_name }}"
    state: present
  become: true


- name: "Python: Installing packages {{ base_telegraf_python_package }}"
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ base_telegraf_python_package }}"
  become: yes


- name: "Python: python{{ base_telegraf_python_version }} -m pip install packages"
  shell: "python{{ base_telegraf_python_version }} -m pip install --proxy='{{ http_proxy }}' {{ item }}"
  with_items:
    - "{{ base_telegraf_pip_modules }}"
  become: yes


