---
scenario:
  name: centos-latest
  create_sequence:
    - create
    - prepare
  check_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
#    - cleanup
    - destroy
  test_sequence:
    - destroy
    - create
    - converge
    # - idempotence
    # - lint
    - verify
    - destroy


dependency:
  name: galaxy

driver:
  name: docker
platforms:
  - name: telegraf-centos-latest
    log: True
    image: redbeard28/docker-centos7-ansible
    pre_build_image: yes
    privileged: True
#    docker_host: tcp://localhost:2376
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  log: True
  playbooks:
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    enabled: False

verifier:
  name: testinfra
  options:
    vvv: true
  additional_files_or_dirs:
    - test/test_*.py
  lint:
    name: flake8
# verifier:
#  name: goss
#  lint:
#    name: yamllint
